default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metall_development
  username: postgres
  password: iam3489495

test:
  <<: *default
  database: metall_test
  username: postgres
  password: iam3489495

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: railway
  username: postgres
  password: DyvrevkDHCjFrMWmKYuCRIISGSQiCyTk
