default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metal_development
  username: postgres
  password: iam3489495

test:
  <<: *default
  database: metal_test
  username: postgres
  password: iam3489495

production:
  <<: *default
  database: metal_production
  username: metal
  password: <%= ENV["METAL_DATABASE_PASSWORD"] %>
