default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metall_development
  username: postgres
  password: iam3489495

test:
  <<: *default
  database: metall_test
  username: postgres
  password: iam3489495

production:
  <<: *default
  url: postgres.railway.internal:5432
  database: railway
  username: postgres
  password: DyvrevkDHCjFrMWmKYuCRIISGSQiCyTk
  # postgresql://postgres:DyvrevkDHCjFrMWmKYuCRIISGSQiCyTk@postgres.railway.internal:5432/railway
  # postgresql://postgres:DyvrevkDHCjFrMWmKYuCRIISGSQiCyTk@monorail.proxy.rlwy.net:22688/railway
